all:
    hosts:
        test_container:
            ansible_host: localhost
            ansible_port: 2222
            ansible_user: root
            ansible_ssh_pass: test123
            ansible_connection: ssh
            ansible_python_interpreter: /usr/bin/python3
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
